/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAffirmationSpeechRouteImport } from './routes/api/affirmation-speech'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffirmationSpeechRoute = ApiAffirmationSpeechRouteImport.update({
  id: '/api/affirmation-speech',
  path: '/api/affirmation-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/affirmation-speech': typeof ApiAffirmationSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/affirmation-speech': typeof ApiAffirmationSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/affirmation-speech': typeof ApiAffirmationSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/affirmation-speech' | '/api/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/affirmation-speech' | '/api/transcribe'
  id: '__root__' | '/' | '/api/affirmation-speech' | '/api/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAffirmationSpeechRoute: typeof ApiAffirmationSpeechRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affirmation-speech': {
      id: '/api/affirmation-speech'
      path: '/api/affirmation-speech'
      fullPath: '/api/affirmation-speech'
      preLoaderRoute: typeof ApiAffirmationSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAffirmationSpeechRoute: ApiAffirmationSpeechRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
